// Config
export const SET_LOADING = 'SET_LOADING';
export const GET_CONFIG = 'GET_CONFIG';
export const SELECTED_MENU = 'SELECTED_MENU';
export const REMOVE_SELECTED_MENU = 'REMOVE_SELECTED_MENU';
export const REMOVE_LOADING = 'REMOVE_LOADING';

// Cast
export const SET_CASTS_LOADING = 'SET_CASTS_LOADING';
export const ADD_CAST = 'ADD_CAST';
export const UPDATE_CAST = 'UPDATE_CAST';
export const GET_CASTS = 'GET_CASTS';
export const DELETE_CAST = 'DELETE_CAST';
export const REMOVE_CASTS_LOADING = 'REMOVE_CASTS_LOADING';

// Genre
export const SET_GENRES_LOADING = 'SET_GENRES_LOADING';
export const ADD_GENRE = 'ADD_GENRE';
export const GET_GENRES = 'GET_GENRES';
export const DELETE_GENRE = 'DELETE_GENRE';
export const REMOVE_GENRES_LOADING = 'REMOVE_GENRES_LOADING';

// User
export const SET_USERS_LOADING = 'SET_USERS_LOADING';
export const GET_USERS = 'GET_USERS';
export const REMOVE_USERS_LOADING = 'REMOVE_USERS_LOADING';

// Movie
export const SET_MOVIES_LOADING = 'SET_MOVIES_LOADING';
export const GET_MOVIES_FOR_ADMIN = 'GET_MOVIES_FOR_ADMIN';
export const GET_MOVIES_BY_SEARCH = 'GET_MOVIES_BY_SEARCH';
export const REMOVE_MOVIES_LOADING = 'REMOVE_MOVIES_LOADING';

// Movie actions
export const SET_MOVIE_ACTION_LOADING = 'SET_MOVIE_ACTION_LOADING';
export const CREATE_MOVIE = 'CREATE_MOVIE';
export const UPDATE_MOVIE_INFO = 'UPDATE_MOVIE_INFO';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const REMOVE_MOVIE_ACTION_LOADING = 'REMOVE_MOVIE_ACTION_LOADING';

// Admin
export const SET_ADMIN_LOADING = 'SET_ADMIN_LOADING';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REMOVE_ADMIN_LOADING = 'REMOVE_ADMIN_LOADING';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
