version: '3.8'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: client
      dockerfile: .
      args:
        - NODE_ENV=NODE_ENV
    command: npm start
    ports:
      - '3000:3000'
    restart: unless-stopped

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=MONGO_PASSWORD
    volumes:
      - mongo-db:/data/db

  api:
    build:
      context: server
      dockerfile: .
      args:
        - NODE_ENV=NODE_ENV
        - PORT=PORT
    command: npm run dev
    ports:
      - '5555:5555'
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo-db:
